import axios from 'axios';
import Head from 'next/head';
import { useCallback, useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [longUrl, setLongUrl] = useState('');
  const [links, setLinks] = useState({});

  const onCreate = async () => {
    await axios.post('/api/shorten', { longUrl });
    setLongUrl('');
    await refreshLinks();
  }

  const onShortUrlClick = (shortLink: string) => {
    const url = `http://localhost:3000/go/${shortLink}`;
    navigator.clipboard.writeText(url)
    .then(
      () => console.log('Copied link to clipboard.'),
      () => console.log('Failed to copy link to clipboard.')
    )
  }

  const getLinks = async () => {
    const res = await axios.get('/api/links')
    return res?.data?.links;
  }

  const refreshLinks = useCallback(async () => {
    const linksObjects = await getLinks();
    setLinks(linksObjects);
  }, []);

  useEffect(() => {
    (async () => {
      await refreshLinks();
    })()
  }, [refreshLinks])

  return (
    <div className={styles.container}>
      <Head>
        <title>Shortener Links</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.mainStyle}>
        <h2 className={styles.title}>
          Shortener links!
        </h2>
        <input
          type='text'
          placeholder='Enter your link'
          value={longUrl}
          onChange={(e) => setLongUrl(e.target.value)}
        />
        <button onClick={onCreate}>Shorten</button>
        <table className={styles.mainTable}>
          <thead>
            <tr>
              <td className={styles.tdBold}>Short url</td>
              <td className={styles.tdBold}>Original url</td>
            </tr>
          </thead>
          <tbody>
            {Object.keys(links).map((short) => {
              const long = links[short]
              return (
                <tr key={short}>
                  <td
                  className={styles.cells}
                    onClick={() => onShortUrlClick(short)}
                  >
                    {`http://localhost:3000/go/${short}`}
                  </td>
                  <td className={styles.cells}>{long}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </main>
    </div>
  );
}
